apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  creationTimestamp: null
  name: labels2
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: labels2 project
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
status: {}

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  creationTimestamp: null
  name: labels2
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        files:
          - path: apps/**/labels2/config.json
        repoURL: https://github.com/gritzkoo/gitops.git
        requeueAfterSeconds: 20
        revision: ""
        template:
          metadata: {}
          spec:
            destination: {}
            project: ""
            source:
              repoURL: ""
    - git:
        files:
          - path: apps/**/labels2/config_dir.json
        repoURL: https://github.com/gritzkoo/gitops.git
        requeueAfterSeconds: 20
        revision: ""
        template:
          metadata: {}
          spec:
            destination: {}
            project: ""
            source:
              directory:
                exclude: "{{ exclude }}"
                include: "{{ include }}"
                jsonnet: {}
                recurse: true
              repoURL: ""
  syncPolicy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: argocd-autopilot
        app.kubernetes.io/name: "{{ .appName }}"
        {{ .labels | toYaml | nident 8 }}
      name: labels2-{{ .userGivenName }}
      namespace: argocd
    spec:
      destination:
        namespace: "{{ .destNamespace }}"
        server: "{{ .destServer }}"
      ignoreDifferences:
        - group: argoproj.io
          jsonPointers:
            - /status
          kind: Application
      project: labels2
      source:
        path: "{{ .srcPath }}"
        repoURL: "{{ .srcRepoURL }}"
        targetRevision: "{{ .srcTargetRevision }}"
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
status: {}
