---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: morpheus-api
spec:
  selector:
    matchLabels:
      app: morpheus-api
  template:
    metadata:
      labels:
        app: morpheus-api
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: morpheus
            - name: TZ
              value: America/Sao_Paulo
        - name: morpheus-api
          image: morpheus-api:v1
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: NODE_ENV
              value: "development"
            - name: TYPEORM_DEBUG
              value: "true"
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "morpheus"
            - name: API_PORT
              value: "80"
            - name: SOCKET_PORT
              value: "3000"
            - name: TZ
              value: "America/Sao_Paulo"
            - name: FIREBASE_PREFIX
              value: "_devgses"
            - name: FIREBASE_PROJECT_ID
              value: "morpheus-ws"
            - name: FIREBASE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: morpheus-api-secret
                  key: FIREBASE_PRIVATE_KEY
            - name: FIREBASE_CLIENT_EMAIL
              value: "firebase-adminsdk-r5ax7@morpheus-ws.iam.gserviceaccount.com"
            - name: FIREBASE_DATABASE_URL
              value: "https://morpheus-ws-default-rtdb.firebaseio.com"
            - name: FIREBASE_API_URL
              value: "https://identitytoolkit.googleapis.com"
            - name: FIREBASE_API_TOKEN
              value: "AIzaSyDBKYk-QwUVLWHV-vTZORV6Ez8Cm8v8X-g"
            - name: JWT_SECRET
              value: "L0C4S))P&R$3LR3TT"
            - name: JWT_TTL
              value: "86400S"
            - name: TWILIO_ACCOUNT_SID
              value: "AC5f2a43791239c196c48cee41ea6876c2"
            - name: TWILIO_AUTH_TOKEN
              value: "c59e76b7ff2d75b00a6ae674e51a4674"
            - name: TWILIO_PHONE
              value: "+12543555341"
            - name: FLIGHTRADAR24_HOST
              value: "https://data-cloud.flightradar24.com"
            - name: FLIGHTRADAR_WWW_HOST
              value: "https://www.flightradar24.com"
            - name: MAX_REPORT_DATE_GAP
              value: "365"
          ports:
            - containerPort: 80
              name: api
            - containerPort: 3000
              name: socket
---
apiVersion: v1
kind: Service
metadata:
  name: morpheus-api
  labels:
    app: morpheus-api
    version: v1
spec:
  selector:
    app: morpheus-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: socket
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
data:
  FIREBASE_PRIVATE_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tIE1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQzlFVmlrWFV1Mzl3Mk0gdjBkSG9oWTl2UDVhL0w2TW9jbXZ0NnNlSjhIWUd2VlU3VFhuNXFobVdSdlo5U081MHg0N3V1LzJsL2pveXJYRyA0b1NTMUhRZTlZZzFFcHM0TUtXWGt4UEFJa3hUY2h0b2ZzMkhtZGRwK0hqRmZtVVZEZ0ZPRkFPajNnYW9KNlduIGsrdnc2dWNyN1VPOU5mOEducUY0UkpJUFllR1BOK1N6RnkrQTYyTGY1TDhvL2U4QWsrMXZvN0VEaVdoeWxOQmMgSU80dzYvWWVxcWh5L2lkTjl0WlM1YWI4YklwTjRXY3ViUmJVd24yekxjanc1Y2VsQmNPT3dTZEJEMW4wRGhGYSBzVkg5bHI4VjZzRElma1RpYStQb3FFZDlCNys2SWYvbFRTNXRmQzhHajl4MDVaZHpyT3JLWmY2R1h4VFl4c256IE93VWJEYzVQQWdNQkFBRUNnZ0VBRGpvVmJQeldPMGdjWFdoeFVTc1p1RmlWM1R2aWpNdUoxUzZoY2puMHBMSFcgbnliZ1pReGV4S0RVN3pBNm1YdVE3VmF5UXVDSnF0N0NFZTZ1b2l2WmR4RHJ5RzZYZm9GdW5IckZSREp3Z3VEMSB2Z1c0cW9rQmhDaGQwaUtpTVpUbHRUM2RUa0hoUjFzQVpKMUZabElPeGlmcTdueDNMY1RYQ3FsQ1FtVVBwNHFnIGowaElPRlJZNVV0bHpEeVE1MnFpNWhyZXEyd1VVTFpqWTJISTZacFBzUzVKdExYRzYydlJtQUVXZ2MvZVpaUU8gdkdIN0xoMzROZGd5cEJkcDQwK0MrTU1QbjJjRTdhVFFVU2duWjlWU3dNS2haQVluOVRHNjJWWmQybVN3ZnIrRiB6R0RWb3E3TU5lNThUTFFmQUY1MktxOGFKYzZrWjZRS09odVF4K3lnRlFLQmdRRGN3MzZ2U1FRREtNN1QvV1BCIDV5R20zc2ROejhJZk1RTEtHdG9JaHBDSkNMaXFKMzJoYk9MK3FaOFhXOWpaNFVSZkl3MHpzWGEyTjFRdVJCa2wgdncxTDJvTlpLUVFsM25wdi9mOW5oYXJlcVd1MmN5cWd0c1VIR09uVlREYW9LazdEcGYzRlBUV3BuODRlRXZTdSA0NVhuWTRvNnNuZlBxWXhrdCttSzBydXBld0tCZ1FEYlByNFZuT3RpcEF1QmNqd0hKem9LR2s3SkZyaWloem1DIHVWYXBzQnVQWDV1NUM2YjAydU5BdG5PZWpwSDNHcVhrVlNld3JOT3hFVnZtNnVIZGV4Q1EwSnZ6dEptOEFWZysgOTBtNkZuK0lsZlFRK0V5cEFZckd2dW5jSUw5Ly9BSFN2ak0vbExOOCt0bG5Oc0ZMbFgyV2dySGhvU1VwMEFhZSA4d1JLb09tRVBRS0JnRWpWbnRoSjZLNzZLYks3S014eWF5SFk0anlEelBIcGc1Z1dYOVRzUUlkVmYwZDBHL2pFIEtlZ0hJbHZjaTZEbXQxNEQvSGtQbGJEc2RET0hlQnlCK2VzS3ZzY054emFQUGlud3pQRGtvc2t2Y0VBVG92Ni8gRGlZWFRCNTVOSmNxemkyeWVCVTQ2cGw2QmREYVJDdm5IaS9uSVZYWVI3c1ZueUlqbzBPUDN5WTlBb0dBUUpzTSBpSEhsS3Z3TUoranhwMm4zd0dKZ05RRnRCdmV5Q3NOeXRpNGU4UERMZ292Y2R1ckpiSmhYR2JJSmNUZDVDdi9NIDRsTUxUbkkvRXB6RVVlK2h3Z3EyNmVtZUk3aUJ1SXhHUFgvRHRRdjdEOFViVWZJU1l0NS9LMDY3SDR1elBkYXUgWTEzK1JpWGxTblRvSU0yOFpFMisvUzN2TlpNSFlHOWNKR0dtYmtFQ2dZQkJXOWxRMTlkeTR2TngxbW04bTE0cSBJd1p5ellxMUc1azlieDJZL0VWT0wvREF4U1lwV3ZWb29tZFFqYmNYTUphdFczdHJCK0hQYmVKbFYrN1p5WVNPIEZJZlIzQlR3aEdJSXY2TzJOOHlHRFNuRG44ekkrRlpNMXMybzg4TFlDVk1QWlNaUDNHR2c3OW9RTGorNHE2QUIgOWIvNXNxblNYOEZSOGQxSVYydTl5Zz09IC0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: morpheus-api-secret
type: Opaque
---

