apiVersion: apps/v1
kind: Deployment
metadata:
  name: morpheus-api
spec:
  selector:
    matchLabels:
      app: morpheus-api
  template:
    metadata:
      labels:
        app: morpheus-api
    spec:
      containers:
        - name: morpheus-api
          image: morpheus-api:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
            - containerPort: 3000
---
kubernetes apiVersion: v1
kind: Service
metadata:
  name: morpheus-api
spec:
  selector:
    app: morpheus-api
  ports:
    - port: 80
      targetPort: 80
    - port: 3000
      targetPort: 3000
