appName: postgres
userGivenName: postgres
destNamespace: postgres
destServer: https://kubernetes.default.svc
srcPath: null
srcRepoURL: https://gritzkoo.github.io/helm-charts
srcTargetRevision: 0.1.0
helm:
  chart: example
  values: |-
    fullnameOverride: postgres
    namespace: postgres
    image:
      repository: postgres
      tag: "latest"
    environments:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres
      - name: POSTGRES_DB
        value: morpheus
      - name: TZ
        value: America/Sao_Paulo
    probes: null
