appName: nginx-live
userGivenName: nginx-live
destNamespace: nginx-live-new
destServer: https://kubernetes.default.svc
srcPath: null
srcRepoURL: https://gritzkoo.github.io/helm-charts
srcTargetRevision: 0.1.0
helm:
  chart: example
  values: |-
    fullnameOverride: test-chart
    namespace: nginx-live-new
    image:
      repository: nginx
      tag: "alpine"

allowEmpty: false