appName: nginx-stg
userGivenName: nginx-stg
destNamespace: nginx-stg
destServer: https://kubernetes.default.svc
srcPath: null
srcRepoURL: https://gritzkoo.github.io/helm-charts
srcTargetRevision: 0.1.0
helm:
  chart: example
  values: |-
    fullnameOverride: test-chart
    namespace: nginx-stg

allowEmpty: false